name: "CI, Build Tests, CD"

on:
  push:
    tags:
      - "*"

jobs:
  unit-and-build-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout repository with LFS
        run: git lfs pull

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install requirements (python)
        run: |
          pip install -r requirements.txt
          pyinstaller --version

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libxcb1 libxkbcommon0 libxcb-shape0 libxcb-keysyms1 libxcb-image0 libxcb-xkb1 libxcb-icccm4 libxcb-cursor0 libxcb-util1 libxcb-render-util0
          
      - name: Linux Build
        run: |
          pyinstaller --onefile --windowed --add-data="UI/Themes/*.qss:UI/Themes" --add-data="Backend/Books_Database/BooksDatabase.db:Backend/Books_Database" --name=BookFinder main.py

      - name: Rename folder
        run: mv dist Application
        
      - name: Create Zip Archive
        run: tar -a -c -f BookFinder.zip Application
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-zip
          path: BookFinder.zip
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            A new release has been pushed. Files included below
          draft: false
          prerelease: false
          
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  #url to upload to
          asset_name: linux.zip #name assigned to the zip
          asset_path: BookFinder.zip  #path to the zip
          asset_content_type: application/zip #zip file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
